// <auto-generated />
namespace Restaurant_Web_App.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class renamedPizzaAndController : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(renamedPizzaAndController));
        
        string IMigrationMetadata.Id
        {
            get { return "202409271054595_renamedPizzaAndController"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
