// <auto-generated />
namespace Restaurant_Web_App.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addedCartClass : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedCartClass));
        
        string IMigrationMetadata.Id
        {
            get { return "202409251238387_addedCartClass"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
